In [2]:
import pandas as pd
import numpy as np

In [3]:
housing_new = pd.read_csv(r"E:\new_project\housing\housing.csv")

In [4]:
housing_new.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [5]:
housing_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [6]:
housing_new['total_bedrooms'].isnull().sum()

207

In [7]:
housing_new[housing_new['total_bedrooms'].isnull()]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
290      -122.16     37.77                47.0       1256.0             NaN   
341      -122.17     37.75                38.0        992.0             NaN   
538      -122.28     37.78                29.0       5154.0             NaN   
563      -122.24     37.75                45.0        891.0             NaN   
696      -122.10     37.69                41.0        746.0             NaN   
...          ...       ...                 ...          ...             ...   
20267    -119.19     34.20                18.0       3620.0             NaN   
20268    -119.18     34.19                19.0       2393.0             NaN   
20372    -118.88     34.17                15.0       4260.0             NaN   
20460    -118.75     34.29                17.0       5512.0             NaN   
20484    -118.72     34.28                17.0       3051.0             NaN   

       population  households  median_income  median_house_value  \
290         570.0       218.0         4.3750            161900.0   
341         732.0       259.0         1.6196             85100.0   
538        3741.0      1273.0         2.5762            173400.0   
563         384.0       146.0         4.9489            247100.0   
696         387.0       161.0         3.9063            178400.0   
...           ...         ...            ...                 ...   
20267      3171.0       779.0         3.3409            220500.0   
20268      1938.0       762.0         1.6953            167400.0   
20372      1701.0       669.0         5.1033            410700.0   
20460      2734.0       814.0         6.6073            258100.0   
20484      1705.0       495.0         5.7376            218600.0   

      ocean_proximity  
290          NEAR BAY  
341          NEAR BAY  
538          NEAR BAY  
563          NEAR BAY  
696          NEAR BAY  
...               ...  
20267      NEAR OCEAN  
20268      NEAR OCEAN  
20372       <1H OCEAN  
20460       <1H OCEAN  
20484       <1H OCEAN  

[207 rows x 10 columns]

In [8]:
housing_new.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [9]:
housing_new['total_bedrooms'].isnull().mean()*100

1.002906976744186

In [10]:
features_with_null = [feature for feature in housing_new.columns if housing_new[feature].isnull().sum()>0]

for feature in features_with_null:
    print(feature, np.round(housing_new['total_bedrooms'].isnull().mean()*100, 3), '% missing values')

total_bedrooms 1.003 % missing values


In [11]:
housing_new.total_bedrooms.mode()[0]

280.0

In [12]:
housing_new.total_bedrooms.fillna(housing_new.total_bedrooms.mode()[0], inplace = True)

In [13]:
housing_new.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [14]:
housing_new.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [15]:
housing_new['rooms_per_house'] = housing_new['total_rooms']/housing_new['households']
#number of bedrooms
housing_new['bedroom_ratio'] = housing_new['total_bedrooms']/housing_new['total_rooms']
# population per house
housing_new['people_per_house'] = housing_new['population']/housing_new['households']

In [16]:
housing_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
 10  rooms_per_house     20640 non-null  float64
 11  bedroom_ratio       20640 non-null  float64
 12  people_per_house    20640 non-null  float64
dtypes: float64(12), object(1)
memory usage: 2.0+ MB


In [17]:
housing_new.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  \
0       322.0       126.0         8.3252            452600.0        NEAR BAY   
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY   
2       496.0       177.0         7.2574            352100.0        NEAR BAY   
3       558.0       219.0         5.6431            341300.0        NEAR BAY   
4       565.0       259.0         3.8462            342200.0        NEAR BAY   

   rooms_per_house  bedroom_ratio  people_per_house  
0         6.984127       0.146591          2.555556  
1         6.238137       0.155797          2.109842  
2         8.288136       0.129516          2.802260  
3         5.817352       0.184458          2.547945  
4         6.281853       0.172096          2.181467

In [18]:
X = housing_new.drop('median_house_value', axis = 1)
y = housing_new['median_house_value']

In [19]:
X.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income ocean_proximity  rooms_per_house  \
0       322.0       126.0         8.3252        NEAR BAY         6.984127   
1      2401.0      1138.0         8.3014        NEAR BAY         6.238137   
2       496.0       177.0         7.2574        NEAR BAY         8.288136   
3       558.0       219.0         5.6431        NEAR BAY         5.817352   
4       565.0       259.0         3.8462        NEAR BAY         6.281853   

   bedroom_ratio  people_per_house  
0       0.146591          2.555556  
1       0.155797          2.109842  
2       0.129516          2.802260  
3       0.184458          2.547945  
4       0.172096          2.181467

In [20]:
y.head()

0    452600.0
1    358500.0
2    352100.0
3    341300.0
4    342200.0
Name: median_house_value, dtype: float64

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=0)
X_train.shape, X_test.shape

((14448, 12), (6192, 12))

In [22]:
X['ocean_proximity'].value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

In [23]:
X.select_dtypes(include = 'O').columns

Index(['ocean_proximity'], dtype='object')

In [24]:
from sklearn.compose import make_column_selector, make_column_transformer

make_column_selector(dtype_include = np.number)

In [25]:
num_features = X.select_dtypes(exclude = "O").columns
cat_features = X.select_dtypes(include = "O").columns

num_features, cat_features

(Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
        'total_bedrooms', 'population', 'households', 'median_income',
        'rooms_per_house', 'bedroom_ratio', 'people_per_house'],
       dtype='object'),
 Index(['ocean_proximity'], dtype='object'))

# Make pipelines

In [26]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_Transformer = StandardScaler()
oneHotEncoder = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oneHotEncoder, cat_features),
        ("StandardScaler", numeric_Transformer, num_features)
    ]
)

preprocessor

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(),
                                 Index(['ocean_proximity'], dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'rooms_per_house', 'bedroom_ratio', 'people_per_house'],
      dtype='object'))])

In [27]:
X_train = preprocessor.fit_transform(X_train)
X_train

array([[ 0.        ,  1.        ,  0.        , ..., -1.146823  ,
         0.63592878,  0.25982829],
       [ 0.        ,  0.        ,  0.        , ..., -0.76585476,
         1.86227174, -0.00327132],
       [ 1.        ,  0.        ,  0.        , ...,  0.46102722,
        -0.75181101,  0.11210392],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.77908241,
        -0.28289375, -0.1818844 ],
       [ 1.        ,  0.        ,  0.        , ..., -0.38591908,
         0.3713204 , -0.1154139 ],
       [ 0.        ,  1.        ,  0.        , ..., -0.65304797,
         1.14499361,  0.05761909]])

In [28]:
X_test = preprocessor.transform(X_test)
X_test

array([[ 0.        ,  0.        ,  0.        , ...,  0.10477153,
        -0.38026424,  0.16599986],
       [ 1.        ,  0.        ,  0.        , ...,  0.29893351,
        -1.02290436, -0.00284492],
       [ 0.        ,  1.        ,  0.        , ...,  0.22177006,
        -0.66564093, -0.01898759],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.93004803,
        -1.39370967, -0.09016131],
       [ 0.        ,  1.        ,  0.        , ...,  0.22501928,
        -0.15677724,  0.10217786],
       [ 1.        ,  0.        ,  0.        , ..., -0.04732252,
        -0.46801453, -0.038109  ]])

## Model Training

1. Linear Regression
2. KNeighbourRegressor
3. DecisionTreeRegressor
4. RandomForestRegressor

In [29]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [30]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square, mse

In [31]:
models = {
    "Linear Regression": LinearRegression(),
    "DecisionTree": DecisionTreeRegressor(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "RandomForest Regressor": RandomForestRegressor()
}

In [32]:
models.keys()

dict_keys(['Linear Regression', 'DecisionTree', 'K-Neighbors Regressor', 'RandomForest Regressor'])

In [33]:
models.values()

dict_values([LinearRegression(), DecisionTreeRegressor(), KNeighborsRegressor(), RandomForestRegressor()])

In [34]:
list(models)

['Linear Regression',
 'DecisionTree',
 'K-Neighbors Regressor',
 'RandomForest Regressor']

In [35]:
len(list(models))

4

In [36]:
for i in range(len(list(models))):
    print(models)

{'Linear Regression': LinearRegression(), 'DecisionTree': DecisionTreeRegressor(), 'K-Neighbors Regressor': KNeighborsRegressor(), 'RandomForest Regressor': RandomForestRegressor()}
{'Linear Regression': LinearRegression(), 'DecisionTree': DecisionTreeRegressor(), 'K-Neighbors Regressor': KNeighborsRegressor(), 'RandomForest Regressor': RandomForestRegressor()}
{'Linear Regression': LinearRegression(), 'DecisionTree': DecisionTreeRegressor(), 'K-Neighbors Regressor': KNeighborsRegressor(), 'RandomForest Regressor': RandomForestRegressor()}
{'Linear Regression': LinearRegression(), 'DecisionTree': DecisionTreeRegressor(), 'K-Neighbors Regressor': KNeighborsRegressor(), 'RandomForest Regressor': RandomForestRegressor()}


In [37]:
for i in range(len(list(models))):
    print(models.values())

dict_values([LinearRegression(), DecisionTreeRegressor(), KNeighborsRegressor(), RandomForestRegressor()])
dict_values([LinearRegression(), DecisionTreeRegressor(), KNeighborsRegressor(), RandomForestRegressor()])
dict_values([LinearRegression(), DecisionTreeRegressor(), KNeighborsRegressor(), RandomForestRegressor()])
dict_values([LinearRegression(), DecisionTreeRegressor(), KNeighborsRegressor(), RandomForestRegressor()])


In [38]:
for i in range(len(list(models))):
    print((list(models.values())[i]))

LinearRegression()
DecisionTreeRegressor()
KNeighborsRegressor()
RandomForestRegressor()


In [39]:
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)
    
    #Prediction
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    print(y_train_pred)
    print(y_test_pred)

[101328. 197072. 285008. ... 241328. 315520.  32400.]
[211584. 282720. 179760. ... 367152.  82432. 266624.]
[ 47500. 100000. 285800. ... 289300. 484600.  69400.]
[160200. 230800. 139200. ... 500001.  72500. 209200.]
[ 63340. 142880. 304120. ... 238100. 408120.  62060.]
[134220.  235600.  130600.  ... 474480.8  79820.  253300. ]
[ 56287.   112027.   290572.   ... 291497.01 452866.04  66735.  ]
[136188.   257603.   135733.   ... 462515.67  74102.   253141.  ]


In [40]:
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)
    
    #Prediction
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    #model evaluation
    train_mae, train_rmse, train_r2_square, train_mse= evaluate_model(y_train, y_train_pred)
    test_mae, test_rmse, test_r2_square, test_mse= evaluate_model(y_test, y_test_pred)
    
    print(list(models.keys())[i])
    
    #evaluation print
    print("Model Performance for Training Data Set----")
    print("1. Mean absolute Error: {:.3f}".format(train_mae))
    print("2. Root Mean Square Error: {:.3f}".format(train_rmse))
    print("3. R2 Square : {:.3f}".format(train_r2_square))
    print("4. Mean Square Error : {:.3f}".format(train_mse))
    print("*********************************************")
    print("Model Performance for Testing Data Set----")
    print("1. Mean absolute Error: {:.3f}".format(test_mae))
    print("2. Root Mean Square Error: {:.3f}".format(test_rmse))
    print("3. R2 Square : {:.3f}".format(test_r2_square))
    print("4. Mean Square Error : {:.3f}".format(test_mse))
    
    print('\n\n')

Linear Regression
Model Performance for Training Data Set----
1. Mean absolute Error: 49231.825
2. Root Mean Square Error: 67898.888
3. R2 Square : 0.654
4. Mean Square Error : 4610258998.716
*********************************************
Model Performance for Testing Data Set----
1. Mean absolute Error: 49134.387
2. Root Mean Square Error: 68976.371
3. R2 Square : 0.643
4. Mean Square Error : 4757739693.770



DecisionTree
Model Performance for Training Data Set----
1. Mean absolute Error: 0.000
2. Root Mean Square Error: 0.000
3. R2 Square : 1.000
4. Mean Square Error : 0.000
*********************************************
Model Performance for Testing Data Set----
1. Mean absolute Error: 45233.990
2. Root Mean Square Error: 71577.482
3. R2 Square : 0.616
4. Mean Square Error : 5123335879.920



K-Neighbors Regressor
Model Performance for Training Data Set----
1. Mean absolute Error: 33316.837
2. Root Mean Square Error: 49562.648
3. R2 Square : 0.815
4. Mean Square Error : 2456456075.69

## Final Model

In [41]:
rforest = RandomForestRegressor(n_estimators=200)

In [42]:
final_model = rforest.fit(X_train, y_train)

## Save the final Model